### ISSUE TITLE
SyntaxError: Unexpected token . (.s-alert-box)

### ISSUE THREAD

**Issue by Method-X** [juliancwirko/react-s-alert#24]
Building in Meteor 1.4.1.2 and getting the following error when importing s-alert.

```
W20161019-03:16:20.432(-4)? (STDERR) .s-alert-box,
W20161019-03:16:20.433(-4)? (STDERR) ^        
W20161019-03:16:20.433(-4)? (STDERR)          
W20161019-03:16:20.433(-4)? (STDERR) SyntaxError: Unexpected token .
W20161019-03:16:20.434(-4)? (STDERR)     at exports.runInThisContext (vm.js:53:16)
W20161019-03:16:20.434(-4)? (STDERR)     at Module._compile (module.js:373:25)
W20161019-03:16:20.434(-4)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20161019-03:16:20.435(-4)? (STDERR)     at Module.load (module.js:343:32)
W20161019-03:16:20.435(-4)? (STDERR)     at Module.Mp.load (/Users/mattmacpherson/.meteor/packages/babel-compiler/.6.9.1_1.15j1r1l++os+web.browser+web.cordova/npm/node_modules/reify/node/runtime.js:16:23)
W20161019-03:16:20.435(-4)? (STDERR)     at Function.Module._load (module.js:300:12)
W20161019-03:16:20.435(-4)? (STDERR)     at Module.require (module.js:353:17)
W20161019-03:16:20.436(-4)? (STDERR)     at require (internal/module.js:12:17)
W20161019-03:16:20.436(-4)? (STDERR)     at npmRequire (/Users/mattmacpherson/Code/edabit/.meteor/local/build/programs/server/npm-require.js:129:10)
W20161019-03:16:20.436(-4)? (STDERR)     at Module.Mp.useNode (packages/modules-runtime/modules-runtime.js:69:1)
```

**Comment by juliancwirko** [comment]
Hi, how you import styles?

**Comment by Method-X** [comment]
Holy cow that was fast! 

In my main App.jsx:

```
import React from 'react';
import ReactDOM from 'react-dom';
import LoginContainer from './ui/login/LoginContainer';
import Alert from 'react-s-alert';
import 'react-s-alert/dist/s-alert-default.css';
import 'react-s-alert/dist/s-alert-css-effects/slide.css';
import 'react-s-alert/dist/s-alert-css-effects/scale.css';
import 'react-s-alert/dist/s-alert-css-effects/bouncyflip.css';
import 'react-s-alert/dist/s-alert-css-effects/flip.css';
import 'react-s-alert/dist/s-alert-css-effects/genie.css';
import 'react-s-alert/dist/s-alert-css-effects/jelly.css';
import 'react-s-alert/dist/s-alert-css-effects/stackslide.css';
```

**Comment by juliancwirko** [comment]
Hmmm, it seems like Meteor can't import the css file. From what I know it should be possible in Meteor js files, but I wonder why you use .jsx files. Do you use some third party Meteor packages to compile react components? Meteor should work well with react and jsx without any third party stuff. 

You could also try to copy css files into the app and test it that way.

**Comment by Method-X** [comment]
I manually put the sAlert css files in my `./client/styles/` directory and it works. I'll update here when I figure out why import isn't working.

**Comment by jorgeer** [comment]
For others encountering this, you are probably accidentally importing the styles on the server. I got this error and found that I had accidentally imported router in an index file, which imported Layout, which imported the styles :P
